name: "OWASP ZAP Scan"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start ZAP
      run: docker run -u zap -p 8080:8080 -d owasp/zap2docker-stable zap.sh -daemon -port 8080 -host 0.0.0.0

    - name: Wait for ZAP to start
      run: sleep 30

    - name: Run ZAP Baseline Scan
      run: |
        docker exec zap zap-baseline.py -t http://localhost:8080 -r zap_report.html
      continue-on-error: true

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report
        path: zap_report.html
